/**
 * jsonlex.tab.c
 * Static constant for character classification table.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include "jsonlex.h"

const jsonlex_charclass_t JSONLEX_CC_TABLE[256] = {
/* 00 */		0, 0, 0, 0, 0, 0, 0, 0,
/* 08 */		0, JSONLEX_CC_WHITE, JSONLEX_CC_WHITE, JSONLEX_CC_WHITE, JSONLEX_CC_WHITE, JSONLEX_CC_WHITE, 0, 0,
/* 10 */		0, 0, 0, 0, 0, 0, 0, 0,
/* 18 */		0, 0, 0, 0, 0, 0, 0, 0,
/* 20 */		JSONLEX_CC_WHITE, 0, JSONLEX_CC_QUOTE, 0, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT /*$*/, 0, 0, JSONLEX_CC_QUOTE,
/* 28 */		JSONLEX_MAKE_TERMCHAR(jsonlex_lparen), JSONLEX_MAKE_TERMCHAR(jsonlex_rparen), 0, JSONLEX_CC_NUMERIC, JSONLEX_MAKE_TERMCHAR(jsonlex_comma), JSONLEX_CC_NUMERIC, JSONLEX_CC_ATTR_INT_SEP, 0,
/* 30 */		JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT,
/* 38 */		JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_NUMERIC|JSONLEX_CC_ATTR_DIGIT|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_MAKE_TERMCHAR(jsonlex_colon), 0, 0, 0, 0, 0,
/* 40 */		0, /*A*/JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT|JSONLEX_CC_ATTR_INT_SEP, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT,
/* 48 */		JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT,
/* 50 */		JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT,
/* 58 */		JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT /*Z*/, JSONLEX_MAKE_TERMCHAR(jsonlex_lbracket), 0, JSONLEX_MAKE_TERMCHAR(jsonlex_rbracket), 0, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT /*_*/,
/* 60 */		0, /*a*/JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT|JSONLEX_CC_ATTR_INT_SEP, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT,
/* 68 */		JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT,
/* 70 */		JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT,
/* 78 */		JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT, JSONLEX_CC_IDCHAR|JSONLEX_CC_ATTR_IDCHAR_CONT /*z*/, JSONLEX_MAKE_TERMCHAR(jsonlex_lbrace), 0, JSONLEX_MAKE_TERMCHAR(jsonlex_rbrace), 0, 0,
/**** 80 ****/
/* 80 */		0, 0, 0, 0, 0, 0, 0, 0,
/* 88 */		0, 0, 0, 0, 0, 0, 0, 0,
/* 90 */		0, 0, 0, 0, 0, 0, 0, 0,
/* 98 */		0, 0, 0, 0, 0, 0, 0, 0,
/* A0 */		0, 0, 0, 0, 0, 0, 0, 0,
/* A8 */		0, 0, 0, 0, 0, 0, 0, 0,
/* B0 */		0, 0, 0, 0, 0, 0, 0, 0,
/* B8 */		0, 0, 0, 0, 0, 0, 0, 0,
/* C0 */		0, 0, 0, 0, 0, 0, 0, 0,
/* C8 */		0, 0, 0, 0, 0, 0, 0, 0,
/* D0 */		0, 0, 0, 0, 0, 0, 0, 0,
/* D8 */		0, 0, 0, 0, 0, 0, 0, 0,
/* E0 */		0, 0, 0, 0, 0, 0, 0, 0,
/* E8 */		0, 0, 0, 0, 0, 0, 0, 0,
/* F0 */		0, 0, 0, 0, 0, 0, 0, 0,
/* F8 */		0, 0, 0, 0, 0, 0, 0, 0,
};
